#!/bin/bash

if [ $# -ne 1 ]
then
echo "Please enter file name. Thank You!"
exit		#  is being maintained as return status for failure
fi

file="myopen.cfg"
file_to_execute=$1
colon_location=0
ext_arr=()
loc_arr=()


while read -r line;
do
colon_location=`expr index "$line" :`

ext_arr+=(${line:0:colon_location-1})
loc_arr+=(${line:colon_location})

done < $file

# At this stage, extensions have been stored independently in ext_arr
# and paths in system directory in loc_arr

dot_location_in_file_name=`expr index "$file_to_execute" .`
file_ext="${file_to_execute:$dot_location_in_file_name}"

loop_count=0
avail_ch=()

for my_ext in "${ext_arr[@]}" 
do

if [ $my_ext == $file_ext ]
then
avail_ch+=${loc_arr[$loop_count]}
echo ${loc_arr[$loop_count]}
fi
let loop_count=loop_count+1
done

echo "${avail_ch[@]}"

# checking for no of extensions. If no of extensions are > 1 prompt a Menu

#if [ "${#avail_ch[@]}" -eq 1 ]
#then
#echo `$( cd "$(dirname "${avail_ch[0]}" )" && pwd )`
#fi



  


